Repository ota-meshi/eslint-plugin-regexp, pull requests merged in 2021-06, with the labels that each got.

#244 Fix false positives for space in RegExp constructor in `regexp/no-invisible-character` rule
  lib/rules/no-invisible-character.ts
  tests/lib/rules/no-invisible-character.ts
Labels: bug

#249 Fix `getUsageOfPattern` to return `unknown` on unknown calls.
  lib/utils/get-usage-of-pattern.ts
  tests/lib/utils/get-usage-of-pattern.ts
Labels: bug

#250 Add `all` configuration
  README.md
  docs/user-guide/README.md
  lib/configs/all.ts
  lib/index.ts
Labels: enhancement

#254 Contributing docs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/new_rule_request.md
  .github/ISSUE_TEMPLATE/other.md
  CONTRIBUTING.md
Labels: documentation

#255 Change `npm run update` to not run tests
  package.json
Labels: enhancement

#259 Fix incorrect pattern parsing when giving RegExp argument to RegExp constructor
  lib/rules/no-useless-flag.ts
  lib/utils/index.ts
  tests/lib/rules/no-useless-assertions.ts
  tests/lib/rules/no-useless-flag.ts
Labels: bug
