Repository ota-meshi/eslint-plugin-regexp, pull requests merged in 2021-08, with the labels that each got.

#282 Improve pattern source information
  lib/rules/control-character-escape.ts
  lib/rules/match-any.ts
  lib/rules/no-empty-alternative.ts
  lib/rules/no-invisible-character.ts
  lib/rules/no-useless-lazy.ts
  lib/rules/optimal-quantifier-concatenation.ts
  lib/rules/prefer-quantifier.ts
  lib/rules/prefer-range.ts
  lib/rules/prefer-w.ts
  lib/rules/sort-character-class-elements.ts
  lib/utils/ast-utils/pattern-source.ts
  lib/utils/ast-utils/utils.ts
  lib/utils/index.ts
  tests/lib/rules/match-any.ts
  tests/lib/rules/negation.ts
  tests/lib/rules/no-empty-alternative.ts
  tests/lib/rules/no-useless-character-class.ts
  tests/lib/rules/no-useless-lazy.ts
  tests/lib/rules/sort-character-class-elements.ts
  tests/lib/utils/ast-utils/extract-expression-references.ts
  tests/lib/utils/ast-utils/extract-property-references.ts
  tests/lib/utils/get-usage-of-pattern.ts
Labels: enhancement

#285 Improves reporting of the `g` and `y` flags in `regexp/no-useless-flag` rule.
  lib/rules/no-useless-flag.ts
  tests/lib/rules/no-useless-flag.ts
Labels: enhancement

#286 Fix replacement escaping in string literals
  lib/utils/ast-utils/pattern-source.ts
  tests/lib/rules/no-useless-character-class.ts
Labels: bug

#287 Support unknown and invalid patterns
  lib/rules/no-non-standard-flag.ts
  lib/rules/sort-flags.ts
  lib/utils/index.ts
  tests/lib/rules/no-non-standard-flag.ts
  tests/lib/rules/sort-flags.ts
Labels: enhancement

#292 Add `strictTypes` option to `regexp/no-useless-flag` rule
  docs/rules/no-useless-flag.md
  lib/rules/no-useless-flag.ts
  lib/utils/type-tracker/index.ts
  tests/lib/rules/no-useless-flag.ts
Labels: enhancement

#241 Removed `disallowNeverMatch` and `alwaysReportExponentialBacktracking` options in `regexp/no-dupe-disjunctions` rule.
  lib/rules/no-dupe-disjunctions.ts
Labels: breaking

#294 Shrink report range of `no-useless-non-capturing-group`
  lib/rules/no-useless-non-capturing-group.ts
  tests/lib/rules/no-useless-non-capturing-group.ts
Labels: enhancement

#293 Fix `no-useless-lazy` for quantifiers with min=0
  lib/rules/no-useless-lazy.ts
  tests/lib/rules/no-useless-lazy.ts
Labels: bug

#295 Use `mention` if necessary
  lib/rules/match-any.ts
  lib/rules/no-dupe-disjunctions.ts
  lib/rules/no-super-linear-backtracking.ts
  lib/rules/no-useless-assertions.ts
  lib/rules/no-useless-backreference.ts
  lib/rules/optimal-lookaround-quantifier.ts
  lib/rules/optimal-quantifier-concatenation.ts
  lib/rules/prefer-d.ts
  lib/rules/prefer-question-quantifier.ts
  lib/rules/prefer-range.ts
  lib/rules/prefer-t.ts
  lib/rules/prefer-w.ts
  lib/rules/strict.ts
  lib/utils/mention.ts
Labels: enhancement

#297 Improve `sort-alternatives`
  lib/rules/sort-alternatives.ts
  tests/lib/rules/sort-alternatives.ts
Labels: enhancement

#305 Add more playground examples
  docs/.vuepress/components/demo/demo-code.js
Labels: documentation, enhancement

#306 Avoid double reporting + flags API improvements
  lib/rules/no-useless-flag.ts
  lib/utils/ast-utils/pattern-source.ts
  lib/utils/index.ts
  tests/lib/rules/no-dupe-characters-character-class.ts
  tests/lib/rules/no-useless-flag.ts
Labels: enhancement
